### PR TITLE
Pinterest added to sharing list

### PR DESCRIPTION
**Pull request by kolappannathan**

### CODE REVIEW

**Comment by shivarajnaidu** [comment]
Thanks for your contribution @kolappannathan .. soon i will review code and will add it to main code :+1:

**Comment by shivarajnaidu** [comment]
@kolappannathan Have you tested it or not kolappan ?

**Comment by kolappannathan** [comment]
@shivarajnaidu I have tested it individually. Such as checked the html page, the URL sharer link is correct, etc... I didn't check it as a whole. I don't have means to compile it as an addon now.

**Comment by shivarajnaidu** [comment]
Thanks @kolappannathan  ...

**Pull request merged**
